### ISSUE TITLE
Mocks for Typescript Types

### ISSUE THREAD

**Issue by sdankel** [Typescript-TDD/ts-auto-mock#145]
Oftentimes I run into issues writing unit tests for my code when it depends on types defined in a third party library. So far I haven't found any solution for this. Types are especially difficult to mock out.

I would love to be able to use this library to mock out TypeScript types. For example, a library has this type defined,

```
export type Producer = Sender & {
  connect(): Promise<void>
  disconnect(): Promise<void>
  ...
}
```

Is there any plans to support types? Thank you!

**Comment by uittorio** [comment]
Hello @sdankel thank you for supporting this library. 

Ts auto mock does support typescript types in almost all scenario, however it does in a different way.

We treat well known interfaces like Promise in a different way, instead of mocking all the properties of a Promise (then, catch, etc..) we create a new Promise manually.

We don't support yet typescript types in intersections or unions

For example

```
type Test = { a: string } & Promise<string>;
createMock<Test>()// this will not be a promise
```

Your scenario is a bit different. Do you mind sharing What is `Sender` so I can have a look?

**Comment by Pmyl** [comment]
The point of this library is to automatically create a mock of any class/interface/type you want (even the `type Producer` in your example),  I think this is what you're looking for

If you want to test it and you need some guidance you can check the [setup](https://github.com/Typescript-TDD/ts-auto-mock/blob/master/docs/TRANSFORMER.md) documentation and the [readme](https://github.com/Typescript-TDD/ts-auto-mock/blob/master/README.md) for usage documentation and for any query you can find us [on slack!](https://join.slack.com/t/typescripttdd/shared_invite/enQtODk3MjQwNzUwNTk2LTMzNjdlZTNmMmY3Nzg2NDNiZDA1YzJmZjk2NjcwZjQwODQ3YzE5NGZjM2Q4MzZjYWNiMWE4MGU0NjEzM2E5YzE)

**Comment by sdankel** [comment]
Thanks! I tried mocking the type and it was returning `undefined`.

I looked through the [docs](https://github.com/Typescript-TDD/ts-auto-mock/blob/master/docs/DETAILS.md) and didn't find an example of a mocked `type`, except when using keyIn and keyOf. Is that what I'd need to do?

Here's the [Producer](https://github.com/tulios/kafkajs/blob/1904481eefe53ce169b38420db59cc68ec819cf7/types/index.d.ts#L467-L478) type I'd like to mock.

**Comment by uittorio** [comment]
@sdankel 

I've tried to mock Producer

``` createMock<Producer>() ```

and it looks correct.

What does return undefined?

Do you mind sharing an example

**Comment by Pmyl** [comment]
The `type` is called "literal" in the docs, we support it but there are some edge cases where we fallback to `undefined`.

The odd part is that Producer and Sender are normal types so it should create the mock normally...

I've installed kafkajs and ran a console log, this is what I get:
```
Object{send: function(){ ... }, sendBatch: function(){ ... }, connect: function(){ ... }, disconnect: function(){ ... }, isIdempo
tent: function(){ ... }, events: Object{CONNECT: 'producer.connect', DISCONNECT: 'producer.disconnect', REQUEST: 'producer.network.req
uest', REQUEST_TIMEOUT: 'producer.network.request_timeout', REQUEST_QUEUE_SIZE: 'producer.network.request_queue_size'}, on: function()
{ ... }, transaction: function(){ ... }, logger: function(){ ... }}
```

My code is:
```ts
import { Producer } from 'kafkajs';
console.log(createMock<Producer>());
```

My configuration is webpack + awesome-typescript-loader + karma


Could you tell us what configuration and the code are you using so that we can investigate?

**Comment by sdankel** [comment]
Oh! I'm seeing that `createMock` itself is undefined. There must a problem with the package installation. I'll go ahead and close this issue.

**Comment by uittorio** [comment]
> Oh! I'm seeing that `createMock` itself is undefined. There must a problem with the package installation. I'll go ahead and close this issue.

If you need any help feel free to ask us on slack :) the installation of a transformer is not that easy
