### ISSUE TITLE
Question: Can we change the defaults?

### ISSUE THREAD

**Issue by adyz** [Typescript-TDD/ts-auto-mock#177]
Hello, 

Awesome idea with this project!

I'm trying to implement this in one of my projects and it seems to work pretty well so far.

I've seen that the mocks generated have these defaults: 
https://github.com/Typescript-TDD/ts-auto-mock/blob/master/docs/DETAILS.md

I'm curious if there is a way to change all the defaults since, for example, an empty string is acting strangely in React and I'd like to have all the strings mapped to something like `Mocked string`.

Thanks!

**Comment by uittorio** [comment]
Hi @adyz thanks for using this library :) 

We currently have a registerMock that can accept Interfaces or types but not primitives.

Is definitely something we could think about it but I would like to understand a bit better your scenario

Could you give me an example in react where you need a specific string?

**Comment by adyz** [comment]
Thank you @uittorio  for the fast reply.


I haven't thought too much about this, but I think that having the possibility to overwrite all the defaults would make me more confident in my tests.


One example is this React component: 


```jsx
function ComponentExample(props: IProps) {
  return props.name ? (
    <h1>
      Name is: <span>{props.name}</span>
    </h1>
  ) : (
    <h1>No name specified</h1>
  );
}
```

If I render this with an empty string or without passing any props, the result would be the same:

```
<div className="App">
      <h1>Name passed as empty string</h1>
      <ComponentExample name="" />
      <hr />

      <h1>Name not passed at all</h1>
      <ComponentExample />

      <hr />
      <h1>Name passed</h1>
      <ComponentExample name="Gigi" />
      <hr />
    </div>
```

I've created a code sandbox here: https://codesandbox.io/s/goofy-stonebraker-7i1j3

The first two examples have the same result and I can't know for sure in my test if this is because I did not pass the prop at all or if it's just an empty string provided by my mock.

This has some workarounds but changing this default to a random string or some other string would give me confidence that my tests don't run into this kind of issue.

**Comment by uittorio** [comment]
I'll share this possible feature with @Pmyl  and I'll let you know... in the mean time you can use 

```ts
createMock<IProps>({name: "my string:}). 
```
this will merge the specified properties (name) with the one you provide

**Comment by adyz** [comment]
Thanks!
Yes, I've used this and it works great!

**Comment by Pmyl** [comment]
At the beginning I thought you were talking about [Monkey Testing](https://en.wikipedia.org/wiki/Monkey_testing) that is something I'm thinking about to implement at some point, thanks for reminding me of that!

...but even with Monkey Testing anyway you could end up with an empty string because the empty strings are still a valid input for your component prop.

I think if you know that you're testing with a non-empty string you should use what uittorio proposed, that's what I would do in my project anyway!
The benefit of having default values is to make sure the 'mock' you're passing around doesn't fail, if you need a specific value then you specify it

**Comment by uittorio** [comment]
@adyz Let us know if you need anything else. 
@Pmyl added a note on our roadmap for monkey testing.

If you think this is not anymore an issue please close it :)

**Comment by uittorio** [comment]
As discussed we've included this issue in the roadmap

https://github.com/Typescript-TDD/ts-auto-mock/blob/master/ROADMAP.md#new-features

Closing this issue because defining the default manually its good enough :)

**Comment by ChristianKlima** [comment]
We are testing our Angular-UI with cypress. To mock our backend we use factories in which we set default values. It would save us a lot of code if we could use this api. Unfortunately, you cannot change the default values. Empty strings are not an alternative, since an empty string can also simply indicate that the value has not been set (it doesn't have to come from the backend then). The random function doesn't help either, since our tests are based on fixed values. I think it wouldn't be difficult to make the default values ​​configurable? It would really help us a lot.
