### ISSUE TITLE
Interface extends type with itself as generic - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Pmyl** [Typescript-TDD/ts-auto-mock#183]
```ts
interface InterfaceWithGenerics<T> {

}

interface ItBreaks extends InterfaceWithGenerics<ItBreaks> {

}

createMock<ItBreaks>(); // maximum call stack size exceeded
```

An example of this can be found in `@types/jquery -> misc.d.ts -> interface Animation<TElement> extends ...`

**Comment by uittorio** [comment]
This issue is partially resolved or at least is rescoped to the fact that we don't support yet circular dependencies in generics, specifically a type that has itself in the generics.

@martinjlowm is working on a PR that will give us this functionality. 

In the meantime the feature is not supported and is documented [here](https://typescript-tdd.github.io/ts-auto-mock/types-not-supported#circular-generics)
