### ISSUE TITLE
extends typescript libs

### ISSUE THREAD

**Issue by uittorio** [Typescript-TDD/ts-auto-mock#4]
I wrote some test scenario with jasmine to simplify the explanation
``` ts
describe('extends typescript libs', () => {
	interface Interface extends Array<string> {
		b: string;
	}
		
	it('should work', () => {
		const properties: Mock<Interface> = createMock<Interface>();
		expect(properties).toBe(""); // it does not
	});
});

```

**Comment by Pmyl** [comment]
This is definitely the same problem as #5 where the transformer is trying to mock entirely `Array<string>` but is failing because is trying to use `[Symbol.iterator]` as a variable name.

That shouldn't happen at all since the `Array` is mocked in a special way.

What we probably have to do is to treat extends/implements in the same way as we treat intersection and then, as specified in #5, review the approach to the problem to avoid breakage and code repetition (example of repetition is two interfaces that extends the same `CommonInterface` where we will going to write twice the code to mock `CommonInterface`).

**Comment by Pmyl** [comment]
@uittorio From the automation tests I can see that [this is not failing](https://github.com/Typescript-TDD/ts-auto-mock/blob/master/test/transformer/descriptor/extends.test.ts#L73) and it's ignoring the typescript type in the same way it's been doing [for intersections](https://github.com/Typescript-TDD/ts-auto-mock/issues/5).

I think this can be closed unless you want something else to happen, let me know

**Comment by uittorio** [comment]
We can ignore this issue with the assumption that we ignore typescript libs for extensions. If we are happy with that we can close it for now. If in the future we need the functionality we can open a new issue
