### ISSUE TITLE
[Feature] Enhance the logs for unsupported types

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#488]
**Is your feature request related to a problem?**
The configuration option `debug` when set to `console` display a lot of warnings on my project.
Based on the documentation, this option could help to debug and also create PRs for unsupported types.
Yet the log is simply `WARNING: Transformer - Not supported type: TypeOperator - it will convert to null` which basically is useless to identify which problem it is.

**Describe the solution you'd like**
Add more information in the logs about the unsupported types including by priority:
- The name of the type (the minimum to at least know which is supported or not)
- The row in the code where is the problem is
- A link inside the code to reach the issue (could use the row above to transform it as a link)

**Comment by uittorio** [comment]
Hi @C0ZEN , thanks for reporting the issue.

When i try to understand what is the root cause of an error, I actually try to get the type name at least. It's a really good point. There should be a functionality to print the name already but we are not exposing it yet in the logger. Feel free to open a PR if you have time or I'll try to find some time soon

**Comment by C0ZEN** [comment]
@uittorio I could take a look tomorrow to provide a PR.

**Comment by C0ZEN** [comment]
Done in #513.
