### ISSUE TITLE
[Issue] The new version `2.3.5` is causing multiple type of errors

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#498]
### Subject of the issue

- `RangeError: Maximum call stack size exceeded` (wtf)
- `TypeError: Cannot set property 'user' of undefined` on created objects with `createMock` (not logic)

### Your environment
* ts-auto-mock version: 2.3.5
* typescript version: 4.0.2

### Steps to reproduce
Check this [PR](https://github.com/Sonia-corporation/il-est-midi-discord/pull/886) and precisely the [failing action](https://github.com/Sonia-corporation/il-est-midi-discord/pull/886/checks?check_run_id=1048282506).

### Example

```typescript
// @todo remove casting once https://github.com/Typescript-TDD/ts-auto-mock/issues/464 is fixed
client = createMock<Client>({
	user: ({
		setPresence: setPresenceMock,
	} as unknown) as ClientUser,
});

beforeEach((): void => {
	client.user = null; // <= Cannot set property 'user' of undefined
});
```

### Expected behavior
No errors.

### Actual behavior
New errors.

**Comment by uittorio** [comment]
Wow, it could be the fact that we've updated typescript to version 4 :). Hopefully, we will add more tests based on your scenario to cover whatever is failing. I'll try now but I may fix it tomorrow morning

**Comment by C0ZEN** [comment]
@uittorio thank you and don't worry there is no rush on my hand.

**Comment by uittorio** [comment]
From a first look it seems like the issue is related to the createMock inside the partial values

I've reproduce the issue by doing this

```ts
const activity: Activity = createMock<Activity>();

  const presence: Presence = createMock<Presence>({
    activities: [activity],
  });

```

I'll keep you posted :)

**Comment by uittorio** [comment]
this is the actual bug without using discordjs
Unfortunately when we resolve the default values that you provide when creating a mock we are using lodash merge that will trigger all the getter of the mock. In your case, activity has recursive types, causing the mock to explode :) 
```ts
 interface A {
    property: B;
  }

  interface B {
    hello: B;
    prop: string;
  }
  const b: B = createMock<B>();

  const a: A = createMock<A>({
    property: b,
  });

  expect(a.property.prop).toBe('');
```

Quick solution for you? Do not create Activity with createMock, you can do it manually. 
Real solution? Not sure yet, need to investigate if we can merge values without triggering the getter

I'll test with version 2.3.4. I believe the issue is still there. I'll re porpose this issue  if you are happy with that.

**Comment by Pmyl** [comment]
@C0ZEN this issue should be fixed in the new version, if it's still broken let me know!

**Comment by C0ZEN** [comment]
@Pmyl seems like this is fixed, thank you!
